language: scala
scala:
  - 2.11.12
  - 2.12.6
jdk:
  - oraclejdk8
  - openjdk8
script:
  - sbt coverage test coverageReport
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.12.6"'
    condition: '"${TRAVIS_JDK_VERSION}" == "oraclejdk8"'
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
